name: Simple CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Start Gad App
      run:
        docker run -d -p 3001:3000 jaktestowac/gad:latest

    - name: Run all Tests
      run: ./gradlew clean allTests -i

    - name: Upload TestNG reports as artifact
      uses: actions/upload-artifact@v4
      with:
        name: testng-report
        path: lib/build/reports/

    - name: Upload ExtentReports as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: lib/reports/
